# Generated by Django 4.0.5 on 2022-06-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings_choices',
            field=models.CharField(choices=[('Uni', 'Unidades'), ('Por', 'Porções'), ('Pes', 'Pessoas')], default='', max_length=12),
        ),
    ]
