# Generated by Django 4.0.5 on 2022-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_preparation_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servings_choices',
            field=models.CharField(choices=[('Uni', 'Unidade(s)'), ('Por', 'Porções'), ('Pes', 'Pessoa(s)')], default='', max_length=12),
        ),
    ]
